travis:
  secure:
    BINSTAR_TOKEN: cLpZIR+Z6lB1QuOvknpyP7PdCS5PCeFiCYGI3SgnFAJbrTm7MX0kLYa4Ce0VRsOVtPQURrAWhWfR8y7GLuiz5kPLXR8OnHP89aPOWhd3uwywTp0VG107oYSVwLXa/1LOFzw84TEiALnnbAvbmdQ5vOi+lghLzpzlcDeoHug+XvYyxGYjYxlcAIV69F3WLyTghwNGCGl9CWMHl8sESMgQIQCMjFtPLH42xKVN1YTlZf/846V9+IOlic41v+Ouga3bc4/e7qu3RkSlSPY3FoBJ5EI9dzEmqcwPdzD5oufx5MD0CCleMs0BbHXKJAREgxE8MMtt/EQPXuWQ0o8K3SXAZY06KSoIoW37lrC7kLx8IvEceGG2G2pi6MSZMqQ13VRpBmYabqoMZY1OACtdGPfGs2L2MUDY03s/YXY0xEWoJWEKzWP780ukxNln7RnDb5q9KRXDZos7ofM7SwQ7PCEuBkWR+Z1ad//JACsTQEtMvMFDMXk6v64xgrh8DWvZt3sEEQMzK8VG+ZRsFTg/NpGUsMrrXAxfLugoEVzcIE5SvtjfTaAgbDdOn9FIqXtVSAqo+Dg6226ajVCeiyZFGKPgRvO7B52CFQK1oJ7amx6SVk9Bz8emm9XZoTtBoQ8J+rjsGgvegyjXPOJhbiyU/G1a9yNufsPs/Itq55pjU7KY4QI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
